jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "admin"
         password: "admin123"
  authorizationStrategy: loggedInUsersCanDoAnything
tool:
  maven:
    installations:
      - name: "Maven 3"
        home: /opt/maven
  git:
    installations:
      - name: Git
        home: "git"

  jdk:
    installations:
      - name: "JDK 11"
        home: /usr/lib/jvm/java-11-openjdk-amd64


jobs:
  - script: |
      job('example 1'){
          scm{
              git {
                  remote {
                      url('https://github.com/ThienNguyenThanh/cosc2767-assignment2-website.git')
                  }
                  branch('main')
              }
          }
          steps {
              maven {
                  rootPOM('pom.xml')
                  goals('clean')
                  goals('install')
                  mavenInstallation('Maven 3')
              }
              publishOverSsh {
                  server('docker-server') {
                      transferSet {
                          sourceFiles('target/*.war')
                          removePrefix('target')
                          execCommand('cd /home/dockeradmin;')
                          execCommand('docker build -t tomcat:test .;')
                          execCommand('docker stop tomcat-container;')
                          execCommand('docker rm tomcat-container;')
                          execCommand('docker run --name tomcat-container -p 8082:8080 --rm tomcat:test')
                      }
                  }
              }
          }
          
      }
